### ISSUE TITLE
[Feature request] Include all the FW txt files

### ISSUE THREAD

**Issue by Doridian** [gokrazy/wifi#2]
Currently, if this module is used on the `gokrazy-community` version, it cannot load the firmware.
The only thing missing on at least my Pi Zero is the `.txt` file. ( See: https://github.com/Doridian/streamdeckpi/blob/main/extrafiles/github.com/gokrazy/wifi/lib/firmware/brcm/brcmfmac43430-sdio.raspberrypi%2Cmodel-zero-w.txt )

I think it might be a good idea to include the `.txt` file for all RPis, as those are small and would make this module work without `extrafiles`, especially if mainline support for 32-bit Pis is ever planned.

**Comment by stapelberg** [comment]
Done, thanks! 

> especially if mainline support for 32-bit Pis is ever planned.

I have no plans for 32-bit Pi support. The Linux upstream kernel only supports the 64-bit Pis, and one important aspect of the gokrazy project is to use an upstream kernel with minimal modifications, and to update it (typically) within the same day that new upstream versions are released.
